SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
  ON C.CAR_TYPE = P.CAR_TYPE 
  AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  -- 1단계: 2022년 11월 1일 ~ 11월 30일 사이에 대여 이력이 겹치지 않는 차량만 선택
  AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
  )
  -- 2단계: 30일간 대여 금액이 50만원 이상 200만원 미만
  AND TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) >= 500000
  AND TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) < 2000000
ORDER BY 
    FEE DESC,          -- 1순위: 대여 금액 내림차순
    C.CAR_TYPE ASC,    -- 2순위: 자동차 종류 오름차순
    C.CAR_ID DESC;     -- 3순위: 자동차 ID 내림차순