-- (1). 재귀를 이용해서 시간 테이블 생성
WITH RECURSIVE TIME_LIST AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_LIST
    WHERE HOUR < 23
)

-- (2). 'ANIMAL_OUT' 테이블을 LEFT JOIN 하여 SQL 쿼리 문 생성
SELECT
    T.HOUR AS HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM
    TIME_LIST AS T
LEFT JOIN
    ANIMAL_OUTS AS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY
    T.HOUR
ORDER BY
    T.HOUR;