-- 중고 거래 게시판 정보를 담은 테이블: USED_GOODS_BOARD
-- 중고 거래 게시판 사용자 정보 테이블: USED_GOODS_USER

-- 거래상태(STATUS)가 완료(DONE)로 되어 있는 총 금액(SUM)이 70만원 이상(WHERE)인 사람을 추출해야 함
SELECT
    USER_ID,
    UGU.NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS UGB
LEFT JOIN
    USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE
    UGB.STATUS = 'DONE'
GROUP BY
    UGU.USER_ID, UGU.NICKNAME
HAVING 
    SUM(UGB.PRICE) >= 700000
ORDER BY
    TOTAL_SALES;