SELECT HOUR(DATETIME) AS 'HOUR', -- HOUR(DATETIME) 컬럼을 가져옴
       COUNT(DATETIME) AS 'COUNT' -- COUNT(DATETIME) 컬럼을 가져옴
FROM ANIMAL_OUTS -- ANIMAL_OUTS 테이블에서 
GROUP BY HOUR(DATETIME) -- HOUR(DATETIME) 으로 그룹 묶어줌
HAVING HOUR BETWEEN 9 AND 19 -- HOUR가 9~19 사이의 SUB 쿼리 문
ORDER BY HOUR -- 시간대로 오름차순 정렬 



