-- 코드를 입력하세요
SELECT
    II.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS FH
JOIN
    ICECREAM_INFO AS II ON FH.FLAVOR = II.FLAVOR
GROUP BY
    II.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER -- 총주문량이 작은 순서대로 조회